name: masjid_noor_customer
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.5

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  ionicons: ^0.2.2
  hive_flutter: ^1.1.0
  fluttertoast: ^8.2.6
  auto_size_text: ^3.0.0
  flutter_screenutil: ^5.9.3
  images_picker: ^1.2.11
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  permission_handler: ^9.2.0
  heroicons: ^0.10.0
  flutter_svg: ^2.0.10+1
  supabase_flutter: ^2.5.5
  equatable: ^2.0.5
  bot_toast: ^4.1.3
  go_router: ^14.2.0
  get: ^4.6.6
  pluto_grid: ^8.0.0
  url_strategy: ^0.2.0
  fl_chart: ^0.68.0
  shimmer: ^3.0.0
  window_manager: ^0.3.9
  google_sign_in: ^6.2.1
  app_links: ^6.1.4
  flutter_custom_tabs: ^2.1.0
  url_launcher: ^6.3.0
  mask_text_input_formatter: ^2.9.0
  share_plus: ^10.0.2
  hive: ^2.2.3
  http: ^1.2.1
  connectivity_plus: ^6.0.3
  mobile_scanner: ^5.1.1
  flutter_native_splash: ^2.4.1
  logging: ^1.2.0
  app_settings: ^5.1.1
  webview_flutter: ^4.9.0
  intl: ^0.19.0
  flutter_barcode_listener: ^0.1.4
  carousel_slider: ^5.0.0
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  in_app_update: ^4.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/favicon.png

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/prayer_times/
    - assets/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          style: italic



