// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTncp2eW_eEIWUyATNLYYZiX7sHChX8VA',
    appId: '1:1075918505837:android:c1bbbb595c078f86a4bc64',
    messagingSenderId: '1075918505837',
    projectId: 'noor-mart-433110',
    storageBucket: 'noor-mart-433110.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLrS4VjtRsrgyH-2JuN0MS67ttPXe2uWQ',
    appId: '1:1075918505837:ios:e476a0449b40ba8ba4bc64',
    messagingSenderId: '1075918505837',
    projectId: 'noor-mart-433110',
    storageBucket: 'noor-mart-433110.appspot.com',
    androidClientId: '1075918505837-73v37dovbq6tna0hj43kfn2iivsuf2hf.apps.googleusercontent.com',
    iosClientId: '1075918505837-aplmu6c140t0dj1gn4oe3m1k18i1i1f7.apps.googleusercontent.com',
    iosBundleId: 'com.mehenot.noormart',
  );

}